const NAVIGATOR_MAX_STEPS: number = Number.POSITIVE_INFINITY;
const NAVIGATOR_VERTICAL_COST: number = 1;
const NAVIGATOR_DIAGONAL_COST: number = 1.4;

export {
  NAVIGATOR_MAX_STEPS,
  NAVIGATOR_VERTICAL_COST,
  NAVIGATOR_DIAGONAL_COST,
};
